export const cities2 = [
    { value: 'Aceh Barat', label: 'Aceh Barat' },
    { value: 'Aceh Barat Daya', label: 'Aceh Barat Daya' },
    { value: 'Aceh Besar', label: 'Aceh Besar' },
    { value: 'Aceh Jaya', label: 'Aceh Jaya' },
    { value: 'Aceh Selatan', label: 'Aceh Selatan' },
    { value: 'Aceh Singkil', label: 'Aceh Singkil' },
    { value: 'Aceh Tamiang', label: 'Aceh Tamiang' },
    { value: 'Aceh Tengah', label: 'Aceh Tengah' },
    { value: 'Aceh Tenggara', label: 'Aceh Tenggara' },
    { value: 'Aceh Timur', label: 'Aceh Timur' },
    { value: 'Aceh Utara', label: 'Aceh Utara' },
    { value: 'Agam', label: 'Agam' },
    { value: 'Alor', label: 'Alor' },
    { value: 'Ambon', label: 'Ambon' },
    { value: 'Asahan', label: 'Asahan' },
    { value: 'Asmat', label: 'Asmat' },
    { value: 'Badung', label: 'Badung' },
    { value: 'Balangan', label: 'Balangan' },
    { value: 'Balikpapan', label: 'Balikpapan' },
    { value: 'BandaAceh', label: 'BandaAceh' },
    { value: 'BandarLampung', label: 'BandarLampung' },
    { value: 'Kabupaten Bandung', label: 'Kabupaten Bandung' },
    { value: 'Kota Bandung', label: 'Kota Bandung' },
    { value: 'Bandung Barat', label: 'Bandung Barat' },
    { value: 'Banggai', label: 'Banggai' },
    { value: 'Banggai Kepulauan', label: 'Banggai Kepulauan' },
    { value: 'Banggai Laut', label: 'Banggai Laut' },
    { value: 'Bangka', label: 'Bangka' },
    { value: 'Bangka Barat', label: 'Bangka Barat' },
    { value: 'Bangka Selatan', label: 'Bangka Selatan' },
    { value: 'Bangka Tengah', label: 'Bangka Tengah' },
    { value: 'Bangkalan', label: 'Bangkalan' },
    { value: 'Bangli', label: 'Bangli' },
    { value: 'Banjar', label: 'Banjar' },
    { value: 'Banjar', label: 'Banjar' },
    { value: 'Banjarbaru', label: 'Banjarbaru' },
    { value: 'Banjarmasin', label: 'Banjarmasin' },
    { value: 'Banjarnegara', label: 'Banjarnegara' },
    { value: 'Bantaeng', label: 'Bantaeng' },
    { value: 'Bantul', label: 'Bantul' },
    { value: 'Banyuasin', label: 'Banyuasin' },
    { value: 'Banyumas', label: 'Banyumas' },
    { value: 'Banyuwangi', label: 'Banyuwangi' },
    { value: 'Barito Kuala', label: 'Barito Kuala' },
    { value: 'Barito Selatan', label: 'Barito Selatan' },
    { value: 'Barito Timur', label: 'Barito Timur' },
    { value: 'Barito Utara', label: 'Barito Utara' },
    { value: 'Barru', label: 'Barru' },
    { value: 'Batam', label: 'Batam' },
    { value: 'Batang', label: 'Batang' },
    { value: 'Batanghari', label: 'Batanghari' },
    { value: 'Batu', label: 'Batu' },
    { value: 'Batubara', label: 'Batubara' },
    { value: 'Bau-Bau', label: 'Bau-Bau' },
    { value: 'Kabupaten Bekasi', label: 'Kabupaten Bekasi' },
    { value: 'Kota Bekasi', label: 'Kota Bekasi' },
    { value: 'Belitung', label: 'Belitung' },
    { value: 'Belitung Timur', label: 'Belitung Timur' },
    { value: 'Belu', label: 'Belu' },
    { value: 'Bener Meriah', label: 'Bener Meriah' },
    { value: 'Bengkalis', label: 'Bengkalis' },
    { value: 'Bengkayang', label: 'Bengkayang' },
    { value: 'Bengkulu', label: 'Bengkulu' },
    { value: 'Bengkulu Selatan', label: 'Bengkulu Selatan' },
    { value: 'Bengkulu Tengah', label: 'Bengkulu Tengah' },
    { value: 'Bengkulu Utara', label: 'Bengkulu Utara' },
    { value: 'Berau', label: 'Berau' },
    { value: 'Biak Numfor', label: 'Biak Numfor' },
    { value: 'Kabupaten Bima', label: 'Kabupaten Bima' },
    { value: 'Kota Bima', label: 'Kota Bima' },
    { value: 'Binjai', label: 'Binjai' },
    { value: 'Bintan', label: 'Bintan' },
    { value: 'Bireuen', label: 'Bireuen' },
    { value: 'Bitung', label: 'Bitung' },
    { value: 'Kabupaten Blitar', label: 'Kabupaten Blitar' },
    { value: 'Kota Blitar', label: 'Kota Blitar' },
    { value: 'Blora', label: 'Blora' },
    { value: 'Boalemo', label: 'Boalemo' },
    { value: 'Kabupaten Bogor', label: 'Kabupaten Bogor' },
    { value: 'Kota Bogor', label: 'Kota Bogor' },
    { value: 'Bojonegoro', label: 'Bojonegoro' },
    { value: 'Bolaang Mongondow', label: 'Bolaang Mongondow' },
    { value: 'Bolaang Mongondow Selatan', label: 'Bolaang Mongondow Selatan' },
    { value: 'Bolaang Mongondow Timur', label: 'Bolaang Mongondow Timur' },
    { value: 'Bolaang Mongondow Utara', label: 'Bolaang Mongondow Utara' },
    { value: 'Bombana', label: 'Bombana' },
    { value: 'Bondowoso', label: 'Bondowoso' },
    { value: 'Bone', label: 'Bone' },
    { value: 'Bone Bolango', label: 'Bone Bolango' },
    { value: 'Bontang', label: 'Bontang' },
    { value: 'Boven Digoel', label: 'Boven Digoel' },
    { value: 'Boyolali', label: 'Boyolali' },
    { value: 'Brebes', label: 'Brebes' },
    { value: 'Bukittinggi', label: 'Bukittinggi' },
    { value: 'Buleleng', label: 'Buleleng' },
    { value: 'Bulukumba', label: 'Bulukumba' },
    { value: 'Bulungan', label: 'Bulungan' },
    { value: 'Bungo', label: 'Bungo' },
    { value: 'Buol', label: 'Buol' },
    { value: 'Buru', label: 'Buru' },
    { value: 'Buru Selatan', label: 'Buru Selatan' },
    { value: 'Buton', label: 'Buton' },
    { value: 'Buton Selatan', label: 'Buton Selatan' },
    { value: 'Buton Tengah', label: 'Buton Tengah' },
    { value: 'Buton Utara', label: 'Buton Utara' },
    { value: 'Ciamis', label: 'Ciamis' },
    { value: 'Cianjur', label: 'Cianjur' },
    { value: 'Cilacap', label: 'Cilacap' },
    { value: 'Cilegon', label: 'Cilegon' },
    { value: 'Cimahi', label: 'Cimahi' },
    { value: 'Kabupaten Cirebon', label: 'Kabupaten Cirebon' },
    { value: 'Kota Cirebon', label: 'Kota Cirebon' },
    { value: 'Dairi', label: 'Dairi' },
    { value: 'Deiyai', label: 'Deiyai' },
    { value: 'Deli Serdang', label: 'Deli Serdang' },
    { value: 'Demak', label: 'Demak' },
    { value: 'Denpasar', label: 'Denpasar' },
    { value: 'Depok', label: 'Depok' },
    { value: 'Dharmasraya', label: 'Dharmasraya' },
    { value: 'Dogiyai', label: 'Dogiyai' },
    { value: 'Dompu', label: 'Dompu' },
    { value: 'Donggala', label: 'Donggala' },
    { value: 'Dumai', label: 'Dumai' },
    { value: 'Empat Lawang', label: 'Empat Lawang' },
    { value: 'Ende', label: 'Ende' },
    { value: 'Enrekang', label: 'Enrekang' },
    { value: 'Fakfak', label: 'Fakfak' },
    { value: 'Flores Timur', label: 'Flores Timur' },
    { value: 'Garut', label: 'Garut' },
    { value: 'Gayo Lues', label: 'Gayo Lues' },
    { value: 'Gianyar', label: 'Gianyar' },
    { value: 'Kabupaten Gorontalo', label: 'Kabupaten Gorontalo' },
    { value: 'Kota Gorontalo', label: 'Kota Gorontalo' },
    { value: 'Gorontalo Utara', label: 'Gorontalo Utara' },
    { value: 'Gowa', label: 'Gowa' },
    { value: 'Gresik', label: 'Gresik' },
    { value: 'Grobogan', label: 'Grobogan' },
    { value: 'Gunung Mas', label: 'Gunung Mas' },
    { value: 'Gunungkidul', label: 'Gunungkidul' },
    { value: 'Gunungsitoli', label: 'Gunungsitoli' },
    { value: 'Halmahera Barat', label: 'Halmahera Barat' },
    { value: 'Halmahera Selatan', label: 'Halmahera Selatan' },
    { value: 'Halmahera Tengah', label: 'Halmahera Tengah' },
    { value: 'Halmahera Timur', label: 'Halmahera Timur' },
    { value: 'Halmahera Utara', label: 'Halmahera Utara' },
    { value: 'Hulu Sungai Selatan', label: 'Hulu Sungai Selatan' },
    { value: 'Hulu Sungai Tengah', label: 'Hulu Sungai Tengah' },
    { value: 'Hulu Sungai Utara', label: 'Hulu Sungai Utara' },
    { value: 'Humbang Hasundutan', label: 'Humbang Hasundutan' },
    { value: 'Indragiri Hilir', label: 'Indragiri Hilir' },
    { value: 'Indragiri Hulu', label: 'Indragiri Hulu' },
    { value: 'Indramayu', label: 'Indramayu' },
    { value: 'Intan Jaya', label: 'Intan Jaya' },
    { value: 'Jambi', label: 'Jambi' },
    { value: 'Kabupaten Jayapura', label: 'Kabupaten Jayapura' },
    { value: 'Kota Jayapura', label: 'Kota Jayapura' },
    { value: 'Jayawijaya', label: 'Jayawijaya' },
    { value: 'Jember', label: 'Jember' },
    { value: 'Jembrana', label: 'Jembrana' },
    { value: 'Jeneponto', label: 'Jeneponto' },
    { value: 'Jepara', label: 'Jepara' },
    { value: 'Jombang', label: 'Jombang' },
    { value: 'Kaimana', label: 'Kaimana' },
    { value: 'Kampar', label: 'Kampar' },
    { value: 'Kapuas', label: 'Kapuas' },
    { value: 'Kapuas Hulu', label: 'Kapuas Hulu' },
    { value: 'Karanganyar', label: 'Karanganyar' },
    { value: 'Karangasem', label: 'Karangasem' },
    { value: 'Karawang', label: 'Karawang' },
    { value: 'Karimun', label: 'Karimun' },
    { value: 'Karo', label: 'Karo' },
    { value: 'Katingan', label: 'Katingan' },
    { value: 'Kaur', label: 'Kaur' },
    { value: 'Kayong Utara', label: 'Kayong Utara' },
    { value: 'Kebumen', label: 'Kebumen' },
    { value: 'Kabupaten Kediri', label: 'Kabupaten Kediri' },
    { value: 'Kota Kediri', label: 'Kota Kediri' },
    { value: 'Keerom', label: 'Keerom' },
    { value: 'Kendal', label: 'Kendal' },
    { value: 'Kendari', label: 'Kendari' },
    { value: 'Kepahiang', label: 'Kepahiang' },
    { value: 'Kepulauan Anambas', label: 'Kepulauan Anambas' },
    { value: 'Kepulauan Aru', label: 'Kepulauan Aru' },
    { value: 'Kepulauan Mentawai', label: 'Kepulauan Mentawai' },
    { value: 'Kepulauan Meranti', label: 'Kepulauan Meranti' },
    { value: 'Kepulauan Sangihe', label: 'Kepulauan Sangihe' },
    { value: 'Kepulauan Selayar', label: 'Kepulauan Selayar' },
    { value: 'Kepulauan Siau Tagulandang Biaro', label: 'Kepulauan Siau Tagulandang Biaro' },
    { value: 'Kepulauan Sula', label: 'Kepulauan Sula' },
    { value: 'Kepulauan Talaud', label: 'Kepulauan Talaud' },
    { value: 'Kepulauan Yapen', label: 'Kepulauan Yapen' },
    { value: 'Kerinci', label: 'Kerinci' },
    { value: 'Ketapang', label: 'Ketapang' },
    { value: 'Klaten', label: 'Klaten' },
    { value: 'Klungkung', label: 'Klungkung' },
    { value: 'Kolaka', label: 'Kolaka' },
    { value: 'Kolaka Timur', label: 'Kolaka Timur' },
    { value: 'Kolaka Utara', label: 'Kolaka Utara' },
    { value: 'Konawe', label: 'Konawe' },
    { value: 'Konawe Kepulauan', label: 'Konawe Kepulauan' },
    { value: 'Konawe Selatan', label: 'Konawe Selatan' },
    { value: 'Konawe Utara', label: 'Konawe Utara' },
    { value: 'Kota Administrasi Jakarta Barat', label: 'Kota Administrasi Jakarta Barat' },
    { value: 'Kota Administrasi Jakarta Pusat', label: 'Kota Administrasi Jakarta Pusat' },
    { value: 'Kota Administrasi Jakarta Selatan', label: 'Kota Administrasi Jakarta Selatan' },
    { value: 'Kota Administrasi Jakarta Timur', label: 'Kota Administrasi Jakarta Timur' },
    { value: 'Kota Administrasi Jakarta Utara', label: 'Kota Administrasi Jakarta Utara' },
    { value: 'Kota Administrasi Kepulauan Seribu', label: 'Kota Administrasi Kepulauan Seribu' },
    { value: 'Kotabaru', label: 'Kotabaru' },
    { value: 'Kotamobagu', label: 'Kotamobagu' },
    { value: 'Kotawaringin Barat', label: 'Kotawaringin Barat' },
    { value: 'Kotawaringin Timur', label: 'Kotawaringin Timur' },
    { value: 'Kuantan Singingi', label: 'Kuantan Singingi' },
    { value: 'Kubu Raya', label: 'Kubu Raya' },
    { value: 'Kudus', label: 'Kudus' },
    { value: 'Kulon Progo', label: 'Kulon Progo' },
    { value: 'Kuningan', label: 'Kuningan' },
    { value: 'Kupang', label: 'Kupang' },
    { value: 'Kupang', label: 'Kupang' },
    { value: 'Kutai Barat', label: 'Kutai Barat' },
    { value: 'Kutai Kartanegara', label: 'Kutai Kartanegara' },
    { value: 'Kutai Timur', label: 'Kutai Timur' },
    { value: 'Labuhanbatu', label: 'Labuhanbatu' },
    { value: 'Labuhanbatu Selatan', label: 'Labuhanbatu Selatan' },
    { value: 'Labuhanbatu Utara', label: 'Labuhanbatu Utara' },
    { value: 'Lahat', label: 'Lahat' },
    { value: 'Lamandau', label: 'Lamandau' },
    { value: 'Lamongan', label: 'Lamongan' },
    { value: 'Lampung Barat', label: 'Lampung Barat' },
    { value: 'Lampung Selatan', label: 'Lampung Selatan' },
    { value: 'Lampung Tengah', label: 'Lampung Tengah' },
    { value: 'Lampung Timur', label: 'Lampung Timur' },
    { value: 'Lampung Utara', label: 'Lampung Utara' },
    { value: 'Landak', label: 'Landak' },
    { value: 'Langkat', label: 'Langkat' },
    { value: 'Langsa', label: 'Langsa' },
    { value: 'Lanny Jaya', label: 'Lanny Jaya' },
    { value: 'Lebak', label: 'Lebak' },
    { value: 'Lebong', label: 'Lebong' },
    { value: 'Lembata', label: 'Lembata' },
    { value: 'Lhokseumawe', label: 'Lhokseumawe' },
    { value: 'Lima Puluh Kota', label: 'Lima Puluh Kota' },
    { value: 'Lingga', label: 'Lingga' },
    { value: 'Lombok Barat', label: 'Lombok Barat' },
    { value: 'Lombok Tengah', label: 'Lombok Tengah' },
    { value: 'Lombok Timur', label: 'Lombok Timur' },
    { value: 'Lombok Utara', label: 'Lombok Utara' },
    { value: 'Lubuklinggau', label: 'Lubuklinggau' },
    { value: 'Lumajang', label: 'Lumajang' },
    { value: 'Luwu', label: 'Luwu' },
    { value: 'Luwu Timur', label: 'Luwu Timur' },
    { value: 'Luwu Utara', label: 'Luwu Utara' },
    { value: 'Kabupaten Madiun', label: 'Kabupaten Madiun' },
    { value: 'Kota Madiun', label: 'Kota Madiun' },
    { value: 'Kabupaten Magelang', label: 'Kabupaten Magelang' },
    { value: 'Kota Magelang', label: 'Kota Magelang' },
    { value: 'Magetan', label: 'Magetan' },
    { value: 'Mahakam Ulu', label: 'Mahakam Ulu' },
    { value: 'Majalengka', label: 'Majalengka' },
    { value: 'Majene', label: 'Majene' },
    { value: 'Makassar', label: 'Makassar' },
    { value: 'Malaka', label: 'Malaka' },
    { value: 'Kabupaten Malang', label: 'Kabupaten Malang' },
    { value: 'Kota Malang', label: 'Kota Malang' },
    { value: 'Malinau', label: 'Malinau' },
    { value: 'Maluku Barat Daya', label: 'Maluku Barat Daya' },
    { value: 'Maluku Tengah', label: 'Maluku Tengah' },
    { value: 'Maluku Tenggara', label: 'Maluku Tenggara' },
    { value: 'Maluku Tenggara Barat', label: 'Maluku Tenggara Barat' },
    { value: 'Mamasa', label: 'Mamasa' },
    { value: 'Mamberamo Raya', label: 'Mamberamo Raya' },
    { value: 'Mamberamo Tengah', label: 'Mamberamo Tengah' },
    { value: 'Kabupaten Mamuju', label: 'Kabupaten Mamuju' },
    { value: 'Kota Mamuju', label: 'Kota Mamuju' },
    { value: 'Mamuju Tengah', label: 'Mamuju Tengah' },
    { value: 'Mamuju Utara', label: 'Mamuju Utara' },
    { value: 'Manado', label: 'Manado' },
    { value: 'Mandailing Natal', label: 'Mandailing Natal' },
    { value: 'Manggarai', label: 'Manggarai' },
    { value: 'Manggarai Barat', label: 'Manggarai Barat' },
    { value: 'Manggarai Timur', label: 'Manggarai Timur' },
    { value: 'Manokwari', label: 'Manokwari' },
    { value: 'Manokwari Selatan', label: 'Manokwari Selatan' },
    { value: 'Mappi', label: 'Mappi' },
    { value: 'Maros', label: 'Maros' },
    { value: 'Mataram', label: 'Mataram' },
    { value: 'Maybrat', label: 'Maybrat' },
    { value: 'Medan', label: 'Medan' },
    { value: 'Melawi', label: 'Melawi' },
    { value: 'Mempawah', label: 'Mempawah' },
    { value: 'Merangin', label: 'Merangin' },
    { value: 'Merauke', label: 'Merauke' },
    { value: 'Mesuji', label: 'Mesuji' },
    { value: 'Metro', label: 'Metro' },
    { value: 'Mimika', label: 'Mimika' },
    { value: 'Minahasa', label: 'Minahasa' },
    { value: 'Minahasa Selatan', label: 'Minahasa Selatan' },
    { value: 'Minahasa Tenggara', label: 'Minahasa Tenggara' },
    { value: 'Minahasa Utara', label: 'Minahasa Utara' },
    { value: 'Kabupaten Mojokerto', label: 'Kabupaten Mojokerto' },
    { value: 'Kota Mojokerto', label: 'Kota Mojokerto' },
    { value: 'Morowali', label: 'Morowali' },
    { value: 'Morowali Utara', label: 'Morowali Utara' },
    { value: 'Muara Enim', label: 'Muara Enim' },
    { value: 'Muaro Jambi', label: 'Muaro Jambi' },
    { value: 'Mukomuko', label: 'Mukomuko' },
    { value: 'Muna', label: 'Muna' },
    { value: 'Muna Barat', label: 'Muna Barat' },
    { value: 'Murung Raya', label: 'Murung Raya' },
    { value: 'Musi Banyuasin', label: 'Musi Banyuasin' },
    { value: 'Musi Rawas', label: 'Musi Rawas' },
    { value: 'Musi Rawas Utara', label: 'Musi Rawas Utara' },
    { value: 'Nabire', label: 'Nabire' },
    { value: 'Nagan Raya', label: 'Nagan Raya' },
    { value: 'Nagekeo', label: 'Nagekeo' },
    { value: 'Natuna', label: 'Natuna' },
    { value: 'Nduga', label: 'Nduga' },
    { value: 'Ngada', label: 'Ngada' },
    { value: 'Nganjuk', label: 'Nganjuk' },
    { value: 'Ngawi', label: 'Ngawi' },
    { value: 'Nias', label: 'Nias' },
    { value: 'Nias Barat', label: 'Nias Barat' },
    { value: 'Nias Selatan', label: 'Nias Selatan' },
    { value: 'Nias Utara', label: 'Nias Utara' },
    { value: 'Nunukan', label: 'Nunukan' },
    { value: 'Ogan Ilir', label: 'Ogan Ilir' },
    { value: 'Ogan Komering Ilir', label: 'Ogan Komering Ilir' },
    { value: 'Ogan Komering Ulu', label: 'Ogan Komering Ulu' },
    { value: 'Ogan Komering Ulu Selatan', label: 'Ogan Komering Ulu Selatan' },
    { value: 'Ogan Komering Ulu Timur', label: 'Ogan Komering Ulu Timur' },
    { value: 'Pacitan', label: 'Pacitan' },
    { value: 'Padang', label: 'Padang' },
    { value: 'Padang Lawas', label: 'Padang Lawas' },
    { value: 'Padang Lawas Utara', label: 'Padang Lawas Utara' },
    { value: 'Padang Pariaman', label: 'Padang Pariaman' },
    { value: 'Padangpanjang', label: 'Padangpanjang' },
    { value: 'Padangsidempuan', label: 'Padangsidempuan' },
    { value: 'Pagar Alam', label: 'Pagar Alam' },
    { value: 'Pakpak Bharat', label: 'Pakpak Bharat' },
    { value: 'Palangka Raya', label: 'Palangka Raya' },
    { value: 'Palembang', label: 'Palembang' },
    { value: 'Palopo', label: 'Palopo' },
    { value: 'Palu', label: 'Palu' },
    { value: 'Pamekasan', label: 'Pamekasan' },
    { value: 'Pandeglang', label: 'Pandeglang' },
    { value: 'Pangandaran', label: 'Pangandaran' },
    { value: 'Pangkajene dan Kepulauan', label: 'Pangkajene dan Kepulauan' },
    { value: 'Pangkal Pinang', label: 'Pangkal Pinang' },
    { value: 'Paniai', label: 'Paniai' },
    { value: 'Parepare', label: 'Parepare' },
    { value: 'Pariaman', label: 'Pariaman' },
    { value: 'Parigi Moutong', label: 'Parigi Moutong' },
    { value: 'Pasaman', label: 'Pasaman' },
    { value: 'Pasaman Barat', label: 'Pasaman Barat' },
    { value: 'Paser', label: 'Paser' },
    { value: 'Kabupaten Pasuruan', label: 'Kabupaten Pasuruan' },
    { value: 'Kota Pasuruan', label: 'Kota Pasuruan' },
    { value: 'Pati', label: 'Pati' },
    { value: 'Payakumbuh', label: 'Payakumbuh' },
    { value: 'Pegunungan Arfak', label: 'Pegunungan Arfak' },
    { value: 'Pegunungan Bintang', label: 'Pegunungan Bintang' },
    { value: 'Kabupaten Pekalongan', label: 'Kabupaten Pekalongan' },
    { value: 'Kota Pekalongan', label: 'Kota Pekalongan' },
    { value: 'Pekanbaru', label: 'Pekanbaru' },
    { value: 'Pelalawan', label: 'Pelalawan' },
    { value: 'Pemalang', label: 'Pemalang' },
    { value: 'Pematangsiantar', label: 'Pematangsiantar' },
    { value: 'Penajam Paser Utara', label: 'Penajam Paser Utara' },
    { value: 'Penukal Abab Lematang Ilir', label: 'Penukal Abab Lematang Ilir' },
    { value: 'Pesawaran', label: 'Pesawaran' },
    { value: 'Pesisir Barat', label: 'Pesisir Barat' },
    { value: 'Pesisir Selatan', label: 'Pesisir Selatan' },
    { value: 'Pidie', label: 'Pidie' },
    { value: 'Pidie Jaya', label: 'Pidie Jaya' },
    { value: 'Pinrang', label: 'Pinrang' },
    { value: 'Pohuwato', label: 'Pohuwato' },
    { value: 'Polewali Mandar', label: 'Polewali Mandar' },
    { value: 'Ponorogo', label: 'Ponorogo' },
    { value: 'Pontianak', label: 'Pontianak' },
    { value: 'Poso', label: 'Poso' },
    { value: 'Prabumulih', label: 'Prabumulih' },
    { value: 'Pringsewu', label: 'Pringsewu' },
    { value: 'Kabupaten Probolinggo', label: 'Kabupaten Probolinggo' },
    { value: 'Kota Probolinggo', label: 'Kota Probolinggo' },
    { value: 'Pulang Pisau', label: 'Pulang Pisau' },
    { value: 'Pulau Morotai', label: 'Pulau Morotai' },
    { value: 'Pulau Taliabu', label: 'Pulau Taliabu' },
    { value: 'Puncak', label: 'Puncak' },
    { value: 'Puncak Jaya', label: 'Puncak Jaya' },
    { value: 'Purbalingga', label: 'Purbalingga' },
    { value: 'Purwakarta', label: 'Purwakarta' },
    { value: 'Purworejo', label: 'Purworejo' },
    { value: 'Raja Ampat', label: 'Raja Ampat' },
    { value: 'Rejang Lebong', label: 'Rejang Lebong' },
    { value: 'Rembang', label: 'Rembang' },
    { value: 'Rokan Hilir', label: 'Rokan Hilir' },
    { value: 'Rokan Hulu', label: 'Rokan Hulu' },
    { value: 'Rote Ndao', label: 'Rote Ndao' },
    { value: 'Sabang', label: 'Sabang' },
    { value: 'Sabu Raijua', label: 'Sabu Raijua' },
    { value: 'Salatiga', label: 'Salatiga' },
    { value: 'Samarinda', label: 'Samarinda' },
    { value: 'Sambas', label: 'Sambas' },
    { value: 'Samosir', label: 'Samosir' },
    { value: 'Sampang', label: 'Sampang' },
    { value: 'Sanggau', label: 'Sanggau' },
    { value: 'Sarmi', label: 'Sarmi' },
    { value: 'Sarolangun', label: 'Sarolangun' },
    { value: 'Sawahlunto', label: 'Sawahlunto' },
    { value: 'Sekadau', label: 'Sekadau' },
    { value: 'Seluma', label: 'Seluma' },
    { value: 'Kabupaten Semarang', label: 'Kabupaten Semarang' },
    { value: 'Kota Semarang', label: 'Kota Semarang' },
    { value: 'Seram Bagian Barat', label: 'Seram Bagian Barat' },
    { value: 'Seram Bagian Timur', label: 'Seram Bagian Timur' },
    { value: 'Kabupaten Serang', label: 'Kabupaten Serang' },
    { value: 'Kota Serang', label: 'Kota Serang' },
    { value: 'Serdang Bedagai', label: 'Serdang Bedagai' },
    { value: 'Seruyan', label: 'Seruyan' },
    { value: 'Siak', label: 'Siak' },
    { value: 'Sibolga', label: 'Sibolga' },
    { value: 'Sidenreng Rappang', label: 'Sidenreng Rappang' },
    { value: 'Sidoarjo', label: 'Sidoarjo' },
    { value: 'Sigi', label: 'Sigi' },
    { value: 'Sijunjung', label: 'Sijunjung' },
    { value: 'Sikka', label: 'Sikka' },
    { value: 'Simalungun', label: 'Simalungun' },
    { value: 'Simeulue', label: 'Simeulue' },
    { value: 'Singkawang', label: 'Singkawang' },
    { value: 'Sinjai', label: 'Sinjai' },
    { value: 'Sintang', label: 'Sintang' },
    { value: 'Situbondo', label: 'Situbondo' },
    { value: 'Sleman', label: 'Sleman' },
    { value: 'Kabupaten Solok', label: 'Kabupaten Solok' },
    { value: 'Kota Solok', label: 'Kota Solok' },
    { value: 'Solok Selatan', label: 'Solok Selatan' },
    { value: 'Soppeng', label: 'Soppeng' },
    { value: 'Sorong', label: 'Sorong' },
    { value: 'Sorong Selatan', label: 'Sorong Selatan' },
    { value: 'Sragen', label: 'Sragen' },
    { value: 'Subang', label: 'Subang' },
    { value: 'Subulussalam', label: 'Subulussalam' },
    { value: 'Kabupaten Sukabumi', label: 'Kabupaten Sukabumi' },
    { value: 'Kota Sukabumi', label: 'Kota Sukabumi' },
    { value: 'Sukamara', label: 'Sukamara' },
    { value: 'Sukoharjo', label: 'Sukoharjo' },
    { value: 'Sumba Barat', label: 'Sumba Barat' },
    { value: 'Sumba Barat Daya', label: 'Sumba Barat Daya' },
    { value: 'Sumba Tengah', label: 'Sumba Tengah' },
    { value: 'Sumba Timur', label: 'Sumba Timur' },
    { value: 'Sumbawa', label: 'Sumbawa' },
    { value: 'Sumbawa Barat', label: 'Sumbawa Barat' },
    { value: 'sumber oleh www.lediknas.com ', label: 'sumber oleh www.lediknas.com ' },
    { value: 'Sumedang', label: 'Sumedang' },
    { value: 'Sumenep', label: 'Sumenep' },
    { value: 'Sungai Penuh', label: 'Sungai Penuh' },
    { value: 'Supiori', label: 'Supiori' },
    { value: 'Surabaya', label: 'Surabaya' },
    { value: 'Surakarta', label: 'Surakarta' },
    { value: 'Tabalong', label: 'Tabalong' },
    { value: 'Tabanan', label: 'Tabanan' },
    { value: 'Takalar', label: 'Takalar' },
    { value: 'Tambrauw', label: 'Tambrauw' },
    { value: 'Tana Tidung', label: 'Tana Tidung' },
    { value: 'Tana Toraja', label: 'Tana Toraja' },
    { value: 'Tanah Bumbu', label: 'Tanah Bumbu' },
    { value: 'Tanah Datar', label: 'Tanah Datar' },
    { value: 'Tanah Laut', label: 'Tanah Laut' },
    { value: 'Kabupaten Tangerang', label: 'Kabupaten Tangerang' },
    { value: 'Kota Tangerang', label: 'Kota Tangerang' },
    { value: 'Tangerang Selatan', label: 'Tangerang Selatan' },
    { value: 'Tanggamus', label: 'Tanggamus' },
    { value: 'Tanjung Jabung Barat', label: 'Tanjung Jabung Barat' },
    { value: 'Tanjung Jabung Timur', label: 'Tanjung Jabung Timur' },
    { value: 'Tanjung Pinang', label: 'Tanjung Pinang' },
    { value: 'Tanjungbalai', label: 'Tanjungbalai' },
    { value: 'Tapanuli Selatan', label: 'Tapanuli Selatan' },
    { value: 'Tapanuli Tengah', label: 'Tapanuli Tengah' },
    { value: 'Tapanuli Utara', label: 'Tapanuli Utara' },
    { value: 'Tapin', label: 'Tapin' },
    { value: 'Tarakan', label: 'Tarakan' },
    { value: 'Kabupaten Tasikmalaya', label: 'Kabupaten Tasikmalaya' },
    { value: 'Kota Tasikmalaya', label: 'Kota Tasikmalaya' },
    { value: 'Tebing Tinggi', label: 'Tebing Tinggi' },
    { value: 'Tebo', label: 'Tebo' },
    { value: 'Kabupaten Tegal', label: 'Kabupaten Tegal' },
    { value: 'Kota Tegal', label: 'Kota Tegal' },
    { value: 'Teluk Bintuni', label: 'Teluk Bintuni' },
    { value: 'Teluk Wondama', label: 'Teluk Wondama' },
    { value: 'Temanggung', label: 'Temanggung' },
    { value: 'Ternate', label: 'Ternate' },
    { value: 'Tidore Kepulauan', label: 'Tidore Kepulauan' },
    { value: 'Timor Tengah Selatan', label: 'Timor Tengah Selatan' },
    { value: 'Timor Tengah Utara', label: 'Timor Tengah Utara' },
    { value: 'Toba Samosir', label: 'Toba Samosir' },
    { value: 'Tojo Una-Una', label: 'Tojo Una-Una' },
    { value: 'Tolikara', label: 'Tolikara' },
    { value: 'Toli-Toli', label: 'Toli-Toli' },
    { value: 'Tomohon', label: 'Tomohon' },
    { value: 'Toraja Utara', label: 'Toraja Utara' },
    { value: 'Trenggalek', label: 'Trenggalek' },
    { value: 'Tual', label: 'Tual' },
    { value: 'Tuban', label: 'Tuban' },
    { value: 'Tulang Bawang', label: 'Tulang Bawang' },
    { value: 'Tulang Bawang Barat', label: 'Tulang Bawang Barat' },
    { value: 'Tulungagung', label: 'Tulungagung' },
    { value: 'Wajo', label: 'Wajo' },
    { value: 'Wakatobi', label: 'Wakatobi' },
    { value: 'Waropen', label: 'Waropen' },
    { value: 'Way Kanan', label: 'Way Kanan' },
    { value: 'Wonogiri', label: 'Wonogiri' },
    { value: 'Wonosobo', label: 'Wonosobo' },
    { value: 'Yahukimo', label: 'Yahukimo' },
    { value: 'Yalimo', label: 'Yalimo' },
    { value: 'Yogyakarta', label: 'Yogyakarta' },
]